# .streamlit/secrets.toml

# Key of API used (set model in config.py accordingly)
API_KEY = "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"

# Section for account names and passwords
[passwords]

# Test account (can attempt interview multiple times)
testaccount = "testpw"

# Accounts in study (can attempt interview once)
95u9kr3rm3 = "mr4cl168dq"
8x19twme52 = "fwi5l5q7hy"
d2gvynxrs5 = "3z43x8rg89"
4k3j1ucz56 = "5gm1z6m121"
# add further accounts in the format 'accountname = "password"' here